servers:
  gamesurge:
    host: irc.gamesurge.net
    channel_map:
      "#RedditMC-S": "mcrelay:survival"
      "#RedditMC-P": "mcrelay:p.nerd.nu:25565"
      "#RedditMC-C": "mcrelay:c.nerd.nu:25565"
web:
  channel_map:
    survival: "mcrelay:survival"
    pve: "mcrelay:p.nerd.nu:25565"
    creative: "mcrelay:c.nerd.nu:25565"
  history_size: 100
  history_mode: count
  host: tcp:6969:interface=127.0.0.1
redis_host: localhost
redis_port: 6379
minecraft:
  s:
    host: s.nerd.nu
    name: survival
  p:
    host: p.nerd.nu
    autorun: |
      /msg totemo hi
  c:
    host: c.nerd.nu
mc_user: redacted_user
mc_password: "redacted_password"
